# Generated by Django 4.1.7 on 2023-06-28 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtcpclient',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 28, 14, 44, 25, 723918)),
        ),
        migrations.AlterField(
            model_name='registers',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 28, 14, 44, 25, 724913)),
        ),
        migrations.AlterField(
            model_name='var',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 6, 28, 14, 44, 25, 722919)),
        ),
        migrations.AlterModelTable(
            name='var',
            table='var',
        ),
    ]
