# Generated by Django 4.1.7 on 2023-07-06 10:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_alter_mtcpclient_date_updated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModbusDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=20)),
                ('reg_first', models.IntegerField(blank=True, null=True)),
                ('reg_amount', models.IntegerField(blank=True, null=True)),
                ('date_updated', models.DateTimeField(blank=True, null=True)),
                ('frequency', models.IntegerField(blank=True, null=True)),
                ('enabled', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='mtcpclient',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 6, 12, 54, 31, 43007)),
        ),
        migrations.AlterField(
            model_name='registers',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 6, 12, 54, 31, 44009)),
        ),
        migrations.AlterField(
            model_name='var',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 6, 12, 54, 31, 43007)),
        ),
        migrations.CreateModel(
            name='ModbusDeviceValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('value', models.JSONField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='testapp.modbusdevice')),
            ],
        ),
    ]
