# Generated by Django 4.1.7 on 2023-07-06 11:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_modbusdevice_alter_mtcpclient_date_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modbusdevice',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='modbus_devices', to='testapp.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mtcpclient',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 6, 13, 11, 1, 966526)),
        ),
        migrations.AlterField(
            model_name='registers',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 6, 13, 11, 1, 967527)),
        ),
        migrations.AlterField(
            model_name='var',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 6, 13, 11, 1, 966526)),
        ),
    ]
